services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solidgame_backend
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      PORT: 5001
      NODE_ENV: production
